version: "3"

services:
  main:
    image: "ex-craft:master"
    ports:
      # - "4369:4369"         # EPMD
      - "9100-9105:9100-9105" # Distributed Erlang
    environment:
      MIX_ENV: staging
      ERLANG_OTP_APPLICATION: "ex_craft"
      ERLANG_HOST: "127.0.0.1"
      ERLANG_MIN_PORT: 9100
      ERLANG_MAX_PORT: 9105
      ERLANG_MAX_PROCESSES: 1000000
      ERLANG_COOKIE: "kWuYx41GQu/J+5zJ9FeQ8QDCWvX0VpxwHxPvcTDmlTY="
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
      restart_policy:
        condition: on-failure
        delay: 5s
